array in python

In [3]:
arr = [1,2,3,4,5,6,7]
print(arr)
print(type(arr))

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


In [6]:
#list is hitrogenious
arr =[1,'c',2,2.3]
print(arr)

[1, 'c', 2, 2.3]


#why do we need numpy array 
"""
1) list is slow.
2) list is not continous .
3) list can store hatrogenious element.
"""

In [10]:
import numpy as np

print(np.__version__)

1.26.4


In [15]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [18]:
y = np.array((1,2,3,4,5,))
y = np.array([[1,2],[3,4]])
print(type(y))

<class 'numpy.ndarray'>


In [21]:
print(y.ndim) #print dimension 

2


In [25]:
# check if array have 0 or not if 0 return false , otherwise true
x= [0,1,1,2,2,2,3,4] 
print(np.all(x))

x= [1,1,2,2,2,3,4] 
print(np.all(x))

False
True


In [27]:
a=10
a =10.2
a ="hello"

In [30]:
#create numpy array of float type
x = np.array([0,1,2,3],dtype ='f')
print(x)

[0. 1. 2. 3.]


In [33]:
#compare two np array
x = np.array([3,5])
y = np.array([2,5])

print(np.greater(x,y))

print(np.greater_equal(x,y))

print(np.less(x,y))

print(np.less_equal(x,y))

[ True False]
[ True  True]
[False False]
[False  True]


In [40]:
# Esize of the memory occupied by the array 
x = np.array([[0,1],[2,3]])
print(x.itemsize)
print(x.size)
print(x.shape)
print(x[0])#index access
print(len(x)) #len (arrr)
print(type(x[0]))# version numpy if int32 , int 4 bites
print(type(x))
print("byte: ",x.itemsize*x.size)
print("%d bytes" %(x.itemsize*x.size))

8
4
(2, 2)
[0 1]
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
byte:  32
32 bytes


In [42]:
array = np.arange(30,40)# give range form 30 to 39
print(array)


[30 31 32 33 34 35 36 37 38 39]


In [44]:
array = np.arange(30,40,2)# array form 30 to 39 by jumping by 2
print(array)


[30 32 34 36 38]


In [48]:
array = np.arange (1,21).reshape(2,10)
print(array)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [50]:
# create a 2d  identity matrix
array_2a = np.identity(3)
array_2b = np.eye(3)

print(array_2a)
print(array_2b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
#creteing a 10x10 matrix filled with ones and zeros
x = np.ones((2,4))
y = np.zeros((2,4))
print(x)
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [56]:
# create the 3d matrix containg 5 by default 
z = np.full((3,4),5,dtype ='f')
print(z)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [58]:
x = np.array ([[0,1],[2,3]])
print(x)

print("sum of all elements : ")
print(np.sum(x))

print("sum of each column : ")
print(np.sum(x,axis =0))

print("sum of each row: ")
print(np.sum (x,axis =1))

[[0 1]
 [2 3]]
sum of all elements : 
6
sum of each column : 
[2 4]
sum of each row: 
[1 5]


In [60]:
x = np.array([[3,2],[1,0]])
print(x)

print(np.sort(x,axis = 0))

print(np.sort(x)) # befault axis =1


[[3 2]
 [1 0]]
[[1 0]
 [3 2]]
[[2 3]
 [0 1]]
