In [2]:
# 5a. flatten a matrix in python using numpy
import numpy as np 

x = np.array ([[2,3],[4,5]])
print(x)
print()

#using array.flatten()mathod [1d array ]
y = x.flatten()#1D = flatten the array 
print("5 (a)\n-----")
print(y)


[[2 3]
 [4 5]]

5 (a)
-----
[2 3 4 5]


In [8]:
# 5 b transpose the array
arr = np.array ([[1,2],[3,4]])
print(arr)
print()

out1 = arr.transpose()
out2 = arr.T

print("output of 5(b)")
print("--------------")
print(out1)
print(out2)


[[1 2]
 [3 4]]

output of 5(b)
--------------
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [11]:
# 5c find the most ferequent value in a numpy array 
x = np.array ([1,2,3,4,5,1,2,1,1,1])

print(x)

print("most frequent value in the abouve array : ")
print("\n")

print("Output of 5c")
print("------------")

print(np.bincount(x)) #count the occurance of the code
print(np.bincount(x).max())
print(np.bincount(x).argmax())


[1 2 3 4 5 1 2 1 1 1]
most frequent value in the abouve array : 


Output of 5c
------------
[0 5 2 1 1 1]
5
1


In [13]:
# 5d find the number of occurrence of a sequence in a array 

arr = np.array ([[2,8,9,4],
                 [8,4,9,4],
                 [4,5,9,7],
                 [2,9,4,3]]) #4,4

#countint sequence 
output = repr(arr).count("4, 5, 9, 7") #find surtain sequencen in the array 
#view output
print(output )  

1


In [33]:
# array slicing
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0][:])
print(arr[0][:3])

[1 2 3 4 5]
[1 2 3]
